# Generated by Django 4.2 on 2023-07-22 01:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('codigo', models.UUIDField(db_column='cod_usuario', default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrador?')),
                ('altera_senha', models.BooleanField(default=True, verbose_name='Altera Senha Proximo Login?')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'cad_usuario',
            },
        ),
    ]
