# Generated by Django 4.2 on 2023-07-22 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tabela', '0001_initial'),
        ('conta_bancaria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('codigo', models.UUIDField(db_column='cod_cartao', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=70)),
                ('nro_cartao', models.CharField(max_length=20)),
                ('validade', models.CharField(max_length=5)),
                ('cvc', models.CharField(max_length=3)),
                ('bandeira_cartao', models.ForeignKey(db_column='cod_bandeira_cartao', on_delete=django.db.models.deletion.PROTECT, to='tabela.bandeiracartao')),
                ('conta_bancaria', models.ForeignKey(db_column='cod_conta_bancaria', on_delete=django.db.models.deletion.PROTECT, to='conta_bancaria.contabancaria')),
                ('tipo_cartao', models.ForeignKey(db_column='cod_tipo_cartao', on_delete=django.db.models.deletion.PROTECT, to='tabela.tipocartao')),
                ('usuario', models.ForeignKey(db_column='cod_usuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartãos',
                'db_table': 'cad_cartao',
            },
        ),
    ]
