# Generated by Django 4.2 on 2023-07-22 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tabela', '0001_initial'),
        ('categoria', '0001_initial'),
        ('conta_bancaria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('codigo', models.UUIDField(db_column='cod_lancamento', default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField()),
                ('categoria', models.ForeignKey(db_column='cod_categoria', on_delete=django.db.models.deletion.PROTECT, to='categoria.categoria')),
                ('conta_bancaria', models.ForeignKey(db_column='cod_conta_bancaria', on_delete=django.db.models.deletion.PROTECT, to='conta_bancaria.contabancaria')),
                ('tipo_lancamento', models.ForeignKey(db_column='cod_tipo_lancamento', on_delete=django.db.models.deletion.PROTECT, to='tabela.tipolancamento')),
                ('usuario', models.ForeignKey(db_column='cod_usuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lancamento',
                'verbose_name_plural': 'Lancamentos',
                'db_table': 'cad_lancamento',
            },
        ),
    ]
