# Generated by Django 4.2 on 2023-07-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('codigo', models.CharField(db_column='cod_banco', max_length=5, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'db_table': 'tab_banco',
            },
        ),
        migrations.CreateModel(
            name='TipoCartao',
            fields=[
                ('codigo', models.CharField(db_column='cod_tipo_cartao', max_length=1, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo Cartão',
                'verbose_name_plural': 'Tipos Cartão',
                'db_table': 'tab_tipo_cartao',
            },
        ),
        migrations.CreateModel(
            name='TipoLancamento',
            fields=[
                ('codigo', models.CharField(db_column='cod_tipo_lancamento', max_length=1, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo Lançamento',
                'verbose_name_plural': 'Tipos lançamento',
                'db_table': 'tab_tipo_lancamento',
            },
        ),
    ]
