# Generated by Django 4.2 on 2023-07-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoLancamento',
            fields=[
                ('codigo', models.CharField(db_column='id_tipo_lancamento', max_length=1, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo Lançamento',
                'verbose_name_plural': 'Tipos lançamento',
                'db_table': 'tab_tipo_lancamento',
            },
        ),
    ]
