# Generated by Django 4.2 on 2023-07-21 01:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codigo', models.UUIDField(db_column='id_categoria', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categiorias',
                'db_table': 'cad_categoria',
            },
        ),
    ]
